config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboard#show"
  end
  root to: "homes#show"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]
  resources :shouts, only: [:create, :show] do
    member do
      post "like" => "likes#create"
      delete "unlike" => "likes#destroy"
    end
  end

  resources :users, only: [:create, :show] do
    resources :followers, only: [:index]
    member do
      post "follow" => "followed_users#create"
      delete "unfollow" => "followed_users#destroy"
    end
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following_relationship.rb
class FollowingRelationship < ApplicationRecord
  belongs_to :follower, class_name: "User", counter_cache: :followed_users_count
  belongs_to :followed_user, class_name: "User", counter_cache: :followers_count
end

app/models/guest.rb
class Guest
  def email
    ""
  end

  def liked?(_)
    false
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :shout

  validates :user_id, uniqueness: { scope: :shout_id}
end

app/models/photo_shout.rb
class PhotoShout < ApplicationRecord
  has_attached_file :image, styles: { thumb: "200x200" }

  validates_attachment :image, 
    content_type: {content_type: ["image/jpeg", "image/gif", "image/png"] },
    size: { in: 0..10.megabytes },
    presence: true
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true
  validates :user, presence: true
  default_scope { order(created_at: :desc) }

  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
  validates :body, presence: true, length: { in: 1..144 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true

  has_many :shouts, dependent: :destroy
  has_many :likes
  has_many :liked_shouts, through: :likes, source: :shout
  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: "FollowingRelationship",
    dependent: :destroy
  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: "FollowingRelationship",
    dependent: :destroy
  has_many :followers, through: :follower_relationships

  def timeline_shouts
    Shout.where(user_id: followed_user_ids + [id])
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

  def following?(user)
    followed_user_ids.include?(user.id)
  end

  def like(shout)
    liked_shouts << shout
  end

  def liked?(shout)
    liked_shout_ids.include?(shout.id)
  end

  def unlike(shout)
    liked_shouts.destroy(shout)
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  def current_user
    super || Guest.new
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.timeline_shouts
  end
end

app/controllers/followed_users_controller.rb
class FollowedUsersController < ApplicationController
  def create
    user_to_follow = find_user
    current_user.follow(user_to_follow)
    redirect_to user_to_follow
  end

  def destroy
    user_to_unfollow = find_user
    current_user.unfollow(user_to_unfollow)
    redirect_to user_to_unfollow
  end

  private

  def find_user
    @_user ||= User.find_by(username: params[:id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @user = find_user
    @followers = @user.followers
  end

  private

  def find_user
    @_user ||= User.find_by(username: params[:user_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    render
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_filter :require_login
  def create
    current_user.like(shout)
    redirect_to root_path
  end

  def destroy
    current_user.unlike(shout)
    redirect_to root_path
  end

  private

  def shout
    @_shout ||= Shout.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  private

  def authenticate(_)
    super(session_params)
  end

  def session_params
    { session: session_params_with_email }
  end

  def session_params_with_email
    params.
      require(:session).
      permit(:password).
      merge(email: user.email)
  end

  def user
    User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
  end

  def email_or_username
    params[:session][:email_or_username]
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    shout = current_user.shouts.create(shout_params)
    redirect_to root_path, redirect_options_for(shout)
  end

  def show
    @shouts = Shout.find(params[:id])
  end

  private

  def shout_params
    { content: content_for_params }
  end

  def content_for_params
    case params[:shout][:content_type]
    when "TextShout" then TextShout.new(text_shout_content_params)
    when "PhotoShout" then PhotoShout.new(photo_shout_content_params)
    end
  end

  def text_shout_content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def photo_shout_content_params
    params.require(:shout).require(:content).permit(:image)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: "shouted successfully" }
    else
      { alert: "Could not shout" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def new
    @user = User.new
  end
  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar(user)
    email_digest = Digest::MD5.hexdigest user.email
    gravatar_url = "//www.gravatar.com/avatar/#{email_digest}"

    image_tag gravatar_url
  end
end

app/helpers/shout_helper_helper.rb
module ShoutHelperHelper
  def like_button(shout)
    if current_user.liked?(shout)
      link_to "Unlike", unlike_shout_path(shout), method: :delete
    else
      link_to "Like", like_shout_path(shout), method: :post
    end
  end

  def autolink(text)
    text.gsub(/@\w+/) { |mention| link_to mention, user_path(mention[1..-1]) }.html_safe
  end
end

app/helpers/user_helper.rb
module UserHelper
  def follow_button(user)
    if current_user.following?(user)
      button_to "Unfollow", unfollow_user_path, method: :delete
    else
      button_to "Follow", follow_user_path
    end
  end
end

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>
<%= form_for @shout do |form| %>
  <%= form.hidden_field :content_type, value: "TextShout" %>
  <%= form.fields_for :content do |content_form| %>
    <%= content_form.text_field :body, placeholder: "Shout here", required: true %>
  <% end %>
  <%= form.submit "Shout!" %>
<% end %>
<%= form_for @shout do |form| %>
  <%= form.hidden_field :content_type, value: "PhotoShout" %>
  <%= form.fields_for :content do |content_form| %>
    <%= content_form.file_field :image, required: true %>
  <% end %>
  <%= form.submit "Shout!" %>
<% end %>
<%= render @shouts %>

app/views/followers/index.html.erb
<%= @user.username %>'s Followers <br>
<%= render @followers %>

app/views/homes/show.html.erb
Shoutr

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag(photo_shout.image(:thumb)) %>

app/views/shouts/_shout.html.erb
<div>
  <%= avatar shout.user %>
  <%= link_to shout.username, shout.user %>
  <%= render shout.content %>
  <%= link_to shout do %>
    <%= time_ago_in_words(shout.created_at) %>
  <% end %>
  <%= link_to like_button(shout) %>
</div>

app/views/shouts/show.html.erb
<%= render @shouts %>

app/views/text_shouts/_text_shout.html.erb
<%= autolink text_shout.body %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email, type: 'email' %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= avatar (@user) %>
<h1><%= @user.username %></h1>

<%= follow_button @user %>
<%= link_to "Followers", user_followers_path(@user) %>
<%= render @shouts %>